# Generated by Django 3.2.12 on 2023-08-09 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='created',
            new_name='status',
        ),
    ]
