# Generated by Django 4.2.3 on 2023-08-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_type', models.CharField(max_length=100)),
                ('status', models.TextField(choices=[('A', 'Yes'), ('B', 'No')], default='A', max_length=100)),
                ('description', models.TextField(max_length=2500)),
            ],
        ),
    ]
