# Generated by Django 3.2.12 on 2023-08-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_created_conversation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='chat_type',
            field=models.CharField(max_length=100),
        ),
    ]
