# Generated by Django 4.2.3 on 2023-08-10 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_conversation_chat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='description',
            field=models.TextField(default='default', max_length=250),
            preserve_default=False,
        ),
    ]
