# Generated by Django 4.2.3 on 2023-08-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_conversation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='users',
            field=models.ManyToManyField(to='main_app.user'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='description',
            field=models.TextField(max_length=2500),
        ),
    ]
